photo21/urls.py
# This file is part of photo21
# Copyright (C) 2022  Amicale des élèves de l'ENS Paris-Saclay
# SPDX-License-Identifier: GPL-3.0-or-later

"""photo21 URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.2/topics/http/urls/
"""

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, re_path

from .views import IndexView, MediaAccess

urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("", include("photologue.urls", namespace="photologue")),
    path("accounts/", include("allauth.urls")),
    path("i18n/", include("django.conf.urls.i18n")),
    path("admin/doc/", include("django.contrib.admindocs.urls")),
    path("admin/", admin.site.urls),
]

# In production media are served through NGINX with X-Accel-Redirect
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    urlpatterns.append(
        re_path("^media/(?P<path>.*)", MediaAccess.as_view(), name="media")
    )

photologue/urls.py
# This file is part of photo21
# Copyright (C) 2022  Amicale des élèves de l'ENS Paris-Saclay
# SPDX-License-Identifier: GPL-3.0-or-later

from django.urls import path, re_path

from .views import (
    GalleryArchiveIndexView,
    GalleryDetailView,
    GalleryDownload,
    GalleryUpload,
    GalleryYearArchiveView,
    PhotoDeleteView,
    PhotoDetailView,
    PhotoReportView,
    TagDetail,
)

app_name = "photologue"
urlpatterns = [
    path("tag/<slug:slug>/", TagDetail.as_view(), name="tag-detail"),
    path("gallery/", GalleryArchiveIndexView.as_view(), name="pl-gallery-archive"),
    re_path(
        r"^gallery/(?P<year>\d{4})/$",
        GalleryYearArchiveView.as_view(),
        name="pl-gallery-archive-year",
    ),
    path("gallery/<slug:slug>/", GalleryDetailView.as_view(), name="pl-gallery"),
    path(
        "gallery/<slug:slug>/<int:owner>/",
        GalleryDetailView.as_view(),
        name="pl-gallery-owner",
    ),
    path(
        "gallery/<slug:slug>/download/",
        GalleryDownload.as_view(),
        name="pl-gallery-download",
    ),
    path("photo/<int:pk>/", PhotoDetailView.as_view(), name="pl-photo"),
    path("photo/<int:pk>/delete/", PhotoDeleteView.as_view(), name="pl-photo-delete"),
    path("photo/<int:pk>/report/", PhotoReportView.as_view(), name="pl-photo-report"),
    path("upload/", GalleryUpload.as_view(), name="pl-gallery-upload"),
]

photologue/models.py
# Based on https://github.com/richardbarran/django-photologue/
# by Richard Barran, BSD-3 licensed

import logging
import os
import random
import unicodedata
from datetime import datetime
from functools import partial
from importlib import import_module
from inspect import isclass
from io import BytesIO

import exifread
from django.conf import settings
from django.core.exceptions import ValidationError
from django.core.files.base import ContentFile
from django.core.validators import RegexValidator
from django.db import models
from django.template.defaultfilters import slugify
from django.urls import reverse
from django.utils.encoding import filepath_to_uri, force_str, smart_str
from django.utils.safestring import mark_safe
from django.utils.timezone import now
from django.utils.translation import gettext_lazy as _
from PIL import Image, ImageFile, ImageFilter

logger = logging.getLogger("photologue.models")

# Default limit for gallery.latest
LATEST_LIMIT = getattr(settings, "PHOTOLOGUE_GALLERY_LATEST_LIMIT", None)

# max_length setting for the ImageModel ImageField
IMAGE_FIELD_MAX_LENGTH = getattr(settings, "PHOTOLOGUE_IMAGE_FIELD_MAX_LENGTH", 100)

# Modify image file buffer size.
ImageFile.MAXBLOCK = getattr(settings, "PHOTOLOGUE_MAXBLOCK", 256 * 2**10)

# Look for user function to define file paths
PHOTOLOGUE_PATH = getattr(settings, "PHOTOLOGUE_PATH", None)
if PHOTOLOGUE_PATH is not None:
    if callable(PHOTOLOGUE_PATH):
        get_storage_path = PHOTOLOGUE_PATH
    else:
        parts = PHOTOLOGUE_PATH.split(".")
        module_name = ".".join(parts[:-1])
        module = import_module(module_name)
        get_storage_path = getattr(module, parts[-1])
else:

    def get_storage_path(instance, filename):
        fn = (
            unicodedata.normalize("NFKD", force_str(filename))
            .encode("ascii", "ignore")
            .decode("ascii")
        )
        return os.path.join("photos", fn)


# Exif Orientation values
# Value 0thRow	0thColumn
#   1	top     left
#   2	top     right
#   3	bottom	right
#   4	bottom	left
#   5	left	top
#   6	right   top
#   7	right   bottom
#   8	left    bottom

# Image Orientations (according to EXIF informations) that needs to be
# transposed and appropriate action
IMAGE_EXIF_ORIENTATION_MAP = {
    2: Image.FLIP_LEFT_RIGHT,
    3: Image.ROTATE_180,
    6: Image.ROTATE_270,
    8: Image.ROTATE_90,
}

# Quality options for JPEG images
JPEG_QUALITY_CHOICES = (
    (30, _("Very Low")),
    (40, _("Low")),
    (50, _("Medium-Low")),
    (60, _("Medium")),
    (70, _("Medium-High")),
    (80, _("High")),
    (90, _("Very High")),
)

# choices for new crop_anchor field in Photo
CROP_ANCHOR_CHOICES = (
    ("top", _("Top")),
    ("right", _("Right")),
    ("bottom", _("Bottom")),
    ("left", _("Left")),
    ("center", _("Center (Default)")),
)

IMAGE_TRANSPOSE_CHOICES = (
    ("FLIP_LEFT_RIGHT", _("Flip left to right")),
    ("FLIP_TOP_BOTTOM", _("Flip top to bottom")),
    ("ROTATE_90", _("Rotate 90 degrees counter-clockwise")),
    ("ROTATE_270", _("Rotate 90 degrees clockwise")),
    ("ROTATE_180", _("Rotate 180 degrees")),
)

# Prepare a list of image filters
filter_names = []
for n in dir(ImageFilter):
    klass = getattr(ImageFilter, n)
    if (
        isclass(klass)
        and issubclass(klass, ImageFilter.BuiltinFilter)
        and hasattr(klass, "name")
    ):
        filter_names.append(klass.__name__)
IMAGE_FILTERS_HELP_TEXT = _(
    'Chain multiple filters using the following pattern "FILTER_ONE->FILTER_TWO->FILTER_THREE"'
    ". Image filters will be applied in order. The following filters are available: %s."
    % (", ".join(filter_names))
)

size_method_map = {}


class TagField(models.CharField):
    """Tags have been removed from Photologue, but the migrations still refer to them so this
    Tagfield definition is left here.
    """

    def __init__(self, **kwargs):
        default_kwargs = {"max_length": 255, "blank": True}
        default_kwargs.update(kwargs)
        super().__init__(**default_kwargs)

    def get_internal_type(self):
        return "CharField"


class Gallery(models.Model):
    title = models.CharField(_("title"), max_length=250, unique=True)
    slug = models.SlugField(
        _("title slug"),
        unique=True,
        max_length=250,
        help_text=_('A "slug" is a unique URL-friendly title for an object.'),
    )
    date_start = models.DateField(
        default=now,
        verbose_name=_("start date"),
    )
    date_end = models.DateField(
        blank=True,
        null=True,
        verbose_name=_("end date"),
    )
    description = models.TextField(_("description"), blank=True)
    tags = models.ManyToManyField(
        "photologue.Tag",
        related_name="galleries",
        verbose_name=_("tags"),
        blank=True,
    )
    photos = models.ManyToManyField(
        "photologue.Photo",
        related_name="galleries",
        verbose_name=_("photos"),
        blank=True,
    )

    class Meta:
        ordering = ["-date_start"]
        get_latest_by = "date_start"
        verbose_name = _("gallery")
        verbose_name_plural = _("galleries")

    def __str__(self):
        return f"{ self.title } ({self.date_start})"

    def get_absolute_url(self):
        return reverse("photologue:pl-gallery", args=[self.slug])

    def sample(self, public=True):
        """Return a sample of photos, ordered at random."""
        count = 1
        if count > self.photo_count():
            count = self.photo_count()
        if public:
            photo_set = self.photos.filter(is_public=True)
        else:
            photo_set = self.photos
        return random.sample(list(photo_set), count)

    def photo_count(self, public=True):
        """Return a count of all the photos in this gallery."""
        if public:
            return self.photos.filter(is_public=True).count()
        else:
            return self.photos.count()

    def photo_private_count(self):
        """Return a count of private photos in this gallery."""
        return self.photos.filter(is_public=False).count()

    photo_count.short_description = _("count")
    photo_private_count.short_description = _("private count")


class ImageModel(models.Model):
    image = models.ImageField(
        _("image"), max_length=IMAGE_FIELD_MAX_LENGTH, upload_to=get_storage_path
    )
    date_taken = models.DateTimeField(
        _("date taken"),
        null=True,
        blank=True,
        help_text=_("Date image was taken; is obtained from the image EXIF data."),
    )
    view_count = models.PositiveIntegerField(_("view count"), default=0, editable=False)
    crop_from = models.CharField(
        _("crop from"),
        blank=True,
        max_length=10,
        default="center",
        choices=CROP_ANCHOR_CHOICES,
    )

    class Meta:
        abstract = True

    def exif(self, file=None):
        try:
            if file:
                tags = exifread.process_file(file)
            else:
                with self.image.storage.open(self.image.name, "rb") as file:
                    tags = exifread.process_file(file, details=False)
            return tags
        except Exception:
            return {}

    def admin_thumbnail(self):
        func = getattr(self, "get_admin_thumbnail_url", None)
        if func is None:
            return _('An "admin_thumbnail" photo size has not been defined.')
        else:
            if hasattr(self, "get_absolute_url"):
                return mark_safe(
                    '<a href="{}"><img src="{}"></a>'.format(
                        self.get_absolute_url(), func()
                    )
                )
            else:
                return mark_safe(
                    '<a href="{}"><img src="{}"></a>'.format(self.image.url, func())
                )

    admin_thumbnail.short_description = _("Thumbnail")
    admin_thumbnail.allow_tags = True

    def cache_path(self):
        return os.path.join(os.path.dirname(self.image.name), "cache")

    def cache_url(self):
        if not self.image:
            return ""
        return "/".join([os.path.dirname(self.image.url), "cache"])

    def image_filename(self):
        return os.path.basename(force_str(self.image.name))

    def _get_filename_for_size(self, size):
        size = getattr(size, "name", size)
        base, ext = os.path.splitext(self.image_filename())
        return "".join([base, "_", size, ext])

    def _get_size_photosize(self, size):
        return PhotoSizeCache().sizes.get(size)

    def _get_size_size(self, size):
        photosize = PhotoSizeCache().sizes.get(size)
        if not self.size_exists(photosize):
            self.create_size(photosize)
        try:
            return Image.open(
                self.image.storage.open(self._get_size_filename(size))
            ).size
        except Exception:
            return None

    def _get_size_url(self, size):
        photosize = PhotoSizeCache().sizes.get(size)
        if not self.size_exists(photosize):
            self.create_size(photosize)
        if photosize.increment_count:
            self.increment_count()
        return "/".join(
            [
                self.cache_url(),
                filepath_to_uri(self._get_filename_for_size(photosize.name)),
            ]
        )

    def _get_size_filename(self, size):
        photosize = PhotoSizeCache().sizes.get(size)
        return smart_str(
            os.path.join(self.cache_path(), self._get_filename_for_size(photosize.name))
        )

    def increment_count(self):
        self.view_count += 1
        models.Model.save(self)

    def __getattr__(self, name):
        global size_method_map
        if not size_method_map:
            init_size_method_map()
        di = size_method_map.get(name, None)
        if di is not None:
            result = partial(getattr(self, di["base_name"]), di["size"])
            setattr(self, name, result)
            return result
        else:

photologue/forms.py
# This file is part of photo21
# Copyright (C) 2022  Amicale des élèves de l'ENS Paris-Saclay
# SPDX-License-Identifier: GPL-3.0-or-later

import datetime

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Div, Layout, Submit
from django import forms
from django.utils.text import slugify
from django.utils.translation import gettext_lazy as _

from .models import Gallery, Tag


class MultipleFileInput(forms.ClearableFileInput):
    allow_multiple_selected = True


class MultipleFileField(forms.FileField):
    allowed_extensions = ['jpg', 'jpeg', 'png', 'gif', 'tiff']  # Specify allowed extensions here

    def __init__(self, *args, **kwargs):
        kwargs.setdefault(
            "widget",
            MultipleFileInput(
                attrs={
                    "accept": "image/*",
                    "class": "mb-3",
                }
            ),
        )
        super().__init__(*args, **kwargs)

    def clean(self, data, initial=None):
        single_file_clean = super().clean

        if isinstance(data, (list, tuple)):
            result = [self.validate_file(d, single_file_clean, initial) for d in data]
        else:
            result = self.validate_file(data, single_file_clean, initial)
        return result

    def validate_file(self, file, single_file_clean, initial):
        # Perform the default clean
        cleaned_file = single_file_clean(file, initial)

        # Check the file extension
        extension = file.name.split('.')[-1].lower()
        if extension not in self.allowed_extensions:
            raise forms.ValidationError(
                f"{file.name} has an invalid file extension. "
                f"Allowed extensions are: {', '.join(self.allowed_extensions)}"
            )
        return cleaned_file


class UploadForm(forms.Form):
    file_field = MultipleFileField(label="")
    gallery = forms.ModelChoiceField(
        Gallery.objects.all(),
        label=_("Gallery"),
        required=False,
        empty_label=_("-- Create a new gallery --"),
        help_text=_(
            "Select a gallery to add these images to. Leave this empty to "
            "create a new gallery from the supplied title."
        ),
    )
    new_gallery_title = forms.CharField(
        label=_("New gallery title"),
        max_length=250,
        required=False,
    )
    new_gallery_date_start = forms.DateField(
        label=_("New gallery event start date"),
        initial=datetime.date.today,
        required=False,
    )
    new_gallery_date_end = forms.DateField(
        label=_("New gallery event end date"),
        initial=datetime.date.today,
        required=False,
    )
    new_gallery_tags = forms.ModelMultipleChoiceField(
        Tag.objects.all(),
        label=_("New gallery tags"),
        required=False,
        help_text=_(
            'Hold down "Control", or "Command" on a Mac, to select more than one.'
        ),
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.use_custom_control = False
        self.helper.layout = Layout(
            "file_field",
            "gallery",
            "new_gallery_title",
            Div(
                Div("new_gallery_date_start", css_class="col"),
                Div("new_gallery_date_end", css_class="col"),
                css_class="row",
            ),
            "new_gallery_tags",
            Submit("submit", _("Upload"), css_class="btn btn-success mt-2"),
        )

    def clean_new_gallery_title(self):
        title = self.cleaned_data["new_gallery_title"]
        if title and Gallery.objects.filter(title=title).exists():
            raise forms.ValidationError(_("A gallery with that title already exists."))
        return title

    def clean(self):
        cleaned_data = super().clean()

        # Check that either an existing gallery is chosen, or new_gallery_title is filled
        if not (
            bool(cleaned_data["gallery"])
            ^ bool(cleaned_data.get("new_gallery_title", None))
        ):
            raise forms.ValidationError(
                _("Select an existing gallery, or enter a title for a new gallery.")
            )

        return cleaned_data

    def get_or_create_gallery(self):
        """
        Get or create gallery
        """
        gallery = self.cleaned_data["gallery"]
        if not gallery:
            # Create new gallery
            title = self.cleaned_data.get("new_gallery_title")
            gallery = Gallery.objects.create(
                title=title,
                slug=slugify(title),
                date_start=self.cleaned_data["new_gallery_date_start"],
                date_end=self.cleaned_data["new_gallery_date_end"],
            )
            for tag in self.cleaned_data["new_gallery_tags"]:
                gallery.tags.add(tag)
        return gallery

photologue/templates/photologue/gallery_archive.html
{% extends "base.html" %}
{% comment %}
This file is part of photo21
Copyright (C) 2022  Amicale des élèves de l'ENS Paris-Saclay
SPDX-License-Identifier: GPL-3.0-or-later
{% endcomment %}
{% load i18n %}

{% block title %}{% trans "Latest photo galleries" %}{% endblock %}

{% block content %}
<div class="row">
    <aside class="col-md-2">
        <h5>{% trans "Filter by year" %}</h5>
        <div class="list-group">
            {% for date in date_list %}
            <a class="list-group-item list-group-item-action" href="{% url 'photologue:pl-gallery-archive-year' date.year %}">{{ date|date:"Y" }}</a>
            {% endfor %}
        </div>
    </aside>
    <main class="col-md-10">
        {% if latest %}
        <div class="row mb-2">
            {% for gallery in latest|slice:":32" %}
            <div class="col-6 col-md-3 mb-2">
                {% include "photologue/includes/gallery_sample.html" %}
            </div>
            {% endfor %}
        </div>
        {% else %}
        <p>{% trans "No galleries were found" %}.</p>
        {% endif %}
    </main>
</div>
{% endblock %}

photologue/templates/photologue/gallery_archive_year.html
{% extends "base.html" %}
{% comment %}
This file is part of photo21
Copyright (C) 2022  Amicale des élèves de l'ENS Paris-Saclay
SPDX-License-Identifier: GPL-3.0-or-later
{% endcomment %}
{% load i18n %}

{% block title %}{% blocktrans with show_year=year|date:"Y" %}Galleries for {{ show_year }}{% endblocktrans %}{% endblock %}

{% block content %}
<div class="row">
    <aside class="col-md-2">
        <h5>{% trans "Filter by year" %}</h5>
        <div class="list-group">
            {% for date in date_list %}
            <a class="list-group-item list-group-item-action{% if date == year %} active{% endif %}" href="{% url 'photologue:pl-gallery-archive-year' date.year %}">{{ date|date:"Y" }}</a>
            {% endfor %}
        </div>
    </aside>
    <main class="col-md-10">
        {% if object_list %}
            <div class="row mb-2">
            {% for gallery in object_list %}
                <div class="col-6 col-md-3 mb-2">
                    {% include "photologue/includes/gallery_sample.html" %}
                </div>
            {% endfor %}
            </div>
        {% else %}
            <p>{% trans "No galleries were found." %}</p>
        {% endif %}
    </main>
</div>
{% endblock %}

photologue/templates/photologue/gallery_detail.html
{% extends "base.html" %}
{% comment %}
This file is part of photo21
Copyright (C) 2022  Amicale des élèves de l'ENS Paris-Saclay
SPDX-License-Identifier: GPL-3.0-or-later
{% endcomment %}
{% load static i18n %}

{% block title %}{{ gallery.title }}{% endblock %}

{% block extracss %}
<link rel="stylesheet" href="{% static 'lightgallery/css/lightgallery.css' %}" />
<link rel="stylesheet" href="{% static 'lightgallery/css/lg-zoom.css' %}" />
<link rel="stylesheet" href="{% static 'lightgallery/css/lg-thumbnail.css' %}" />
{% endblock %}

{% block extrajs %}
{# Javascript code fetches CSRF token from HTML #}
{% csrf_token %}
<input type="hidden" name="is_staff" value="{{ request.user.is_staff|yesno:'true,false' }}">
<script src="{% static 'lightgallery/lightgallery.min.js' %}"></script>
<script src="{% static 'lightgallery/plugins/admin/lg-admin.js' %}"></script>
<script src="{% static 'lightgallery/plugins/hash/lg-hash.min.js' %}"></script>
<script src="{% static 'lightgallery/plugins/thumbnail/lg-thumbnail.min.js' %}"></script>
<script src="{% static 'lightgallery/plugins/zoom/lg-zoom.min.js' %}"></script>
<script src="{% static 'gallery_detail.js' %}"></script>
{% endblock %}

{% block content %}
<h1>
    {{ gallery.title }}
    {% if request.user.is_staff and perms.photologue.change_gallery %}
    <a href="{% url 'admin:photologue_gallery_change' gallery.id %}">
        <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" class="bi bi-gear" viewBox="0 0 16 18">
            <path d="M8 4.754a3.246 3.246 0 1 0 0 6.492 3.246 3.246 0 0 0 0-6.492zM5.754 8a2.246 2.246 0 1 1 4.492 0 2.246 2.246 0 0 1-4.492 0z"/>
            <path d="M9.796 1.343c-.527-1.79-3.065-1.79-3.592 0l-.094.319a.873.873 0 0 1-1.255.52l-.292-.16c-1.64-.892-3.433.902-2.54 2.541l.159.292a.873.873 0 0 1-.52 1.255l-.319.094c-1.79.527-1.79 3.065 0 3.592l.319.094a.873.873 0 0 1 .52 1.255l-.16.292c-.892 1.64.901 3.434 2.541 2.54l.292-.159a.873.873 0 0 1 1.255.52l.094.319c.527 1.79 3.065 1.79 3.592 0l.094-.319a.873.873 0 0 1 1.255-.52l.292.16c1.64.893 3.434-.902 2.54-2.541l-.159-.292a.873.873 0 0 1 .52-1.255l.319-.094c1.79-.527 1.79-3.065 0-3.592l-.319-.094a.873.873 0 0 1-.52-1.255l.16-.292c.893-1.64-.902-3.433-2.541-2.54l-.292.159a.873.873 0 0 1-1.255-.52l-.094-.319zm-2.633.283c.246-.835 1.428-.835 1.674 0l.094.319a1.873 1.873 0 0 0 2.693 1.115l.291-.16c.764-.415 1.6.42 1.184 1.185l-.159.292a1.873 1.873 0 0 0 1.116 2.692l.318.094c.835.246.835 1.428 0 1.674l-.319.094a1.873 1.873 0 0 0-1.115 2.693l.16.291c.415.764-.42 1.6-1.185 1.184l-.291-.159a1.873 1.873 0 0 0-2.693 1.116l-.094.318c-.246.835-1.428.835-1.674 0l-.094-.319a1.873 1.873 0 0 0-2.692-1.115l-.292.16c-.764.415-1.6-.42-1.184-1.185l.159-.291A1.873 1.873 0 0 0 1.945 8.93l-.319-.094c-.835-.246-.835-1.428 0-1.674l.319-.094A1.873 1.873 0 0 0 3.06 4.377l-.16-.292c-.415-.764.42-1.6 1.185-1.184l.292.159a1.873 1.873 0 0 0 2.692-1.115l.094-.319z"/>
        </svg>
    </a>
    {% endif %}
</h1>
{% if gallery.date_start %}<p class="text-muted small">{{ gallery.date_start }}{% if gallery.date_end and gallery.date_end != gallery.date_start %} {% trans "to" %} {{ gallery.date_end }}{% endif %}</p>{% endif %}
{% if request.user.is_staff and gallery.photo_private_count %}<p class="text-danger small">{{ gallery.photo_private_count }} photos censurées</p>{% endif %}
{% if gallery.tags.all %}
<p class="text-muted">
    Tags : {% for tag in gallery.tags.all %}
    <a class="badge rounded-pill bg-body-tertiary text-decoration-none" href="{% url 'photologue:tag-detail' tag.slug %}">{{ tag }}</a>
    {% endfor %}
</p>
{% endif %}
{% if gallery.description %}<p>{{ gallery.description|safe }}</p>{% endif %}

<div class="card">
    <div class="card-header pb-0 border-bottom-0">
        <ul class="nav nav-tabs">
            <li class="nav-item">
                {% url 'photologue:pl-gallery' gallery.slug as url %}
                <a class="nav-link {% if request.path_info == url %}active{% endif %}" href="{{ url }}">
                    {% trans "All pictures" %}
                </a>
            </li>
            {% for owner in owners %}
            <li class="nav-item">
                {% url 'photologue:pl-gallery-owner' slug=gallery.slug owner=owner.id as url %}
                <a class="nav-link {% if request.path_info == url %}active{% endif %}" href="{{ url }}">
                    {% if owner.get_full_name %}{{ owner.get_full_name }}{% else %}{{ owner.username }}{% endif %}
                </a>
            </li>
            {% endfor %}
        </ul>
    </div>
    <div class="card-body row" id="lightgallery">
        {% for photo in photos %}
        <a class="col-6 col-md-3 mb-2 text-center" href="{{ photo.get_absolute_url }}" data-src="{{ photo.get_display_url }}" data-download-url="{{ photo.image.url }}" data-slide-name="{{ photo.id }}">
            <img src="{{ photo.get_thumbnail_url }}" loading="lazy" class="img-thumbnail p-0{% if not photo.is_public %} border-danger border-5{% endif %}" alt="{{ photo.title }}{% if photo.date_taken %} - {{ photo.date_taken|date }} {{ photo.date_taken|time }}{% endif %}{% if photo.owner.get_full_name %} - {{ photo.owner.get_full_name }}{% else %} - {{ photo.owner.username }}{% endif %}{% if photo.license %} - {{ photo.license }}{% endif %}{% if not photo.is_public %} - !PRIVATE!{% endif %}">
        </a>
        {% endfor %}
    </div>
    <div class="card-footer">
        <a href="{% url 'photologue:pl-gallery-download' gallery.slug %}" class="btn btn-secondary btn-sm">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-download" viewBox="0 0 16 16">
                <path d="M.5 9.9a.5.5 0 0 1 .5.5v2.5a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1v-2.5a.5.5 0 0 1 1 0v2.5a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2v-2.5a.5.5 0 0 1 .5-.5z"/>
                <path d="M7.646 11.854a.5.5 0 0 0 .708 0l3-3a.5.5 0 0 0-.708-.708L8.5 10.293V1.5a.5.5 0 0 0-1 0v8.793L5.354 8.146a.5.5 0 1 0-.708.708l3 3z"/>
            </svg>
            {% trans 'Download all gallery' %}
        </a>
    </div>
</div>
{% endblock %}

photologue/templates/photologue/photo_confirm_delete.html
{% extends "base.html" %}
{% comment %}
This file is part of photo21
Copyright (C) 2022  Amicale des élèves de l'ENS Paris-Saclay
SPDX-License-Identifier: GPL-3.0-or-later
{% endcomment %}
{% load i18n %}

{% block title %}{% trans "Delete confirmation" %}{% endblock %}

{% block content %}
<div class="row">
    <div class="col-lg-12">
        <h1>{% trans "Delete confirmation" %}</h1>
        <form method="post">{% csrf_token %}
            <p>
                {% blocktrans trimmed %}
                Are you sure you want to delete <code>{{ object }}</code>?
                {% endblocktrans %}
            </p>
            {{ form }}
            <input type="submit" class="btn btn-danger" value="{% trans "Confirm" %}">
        </form>
    </div>
</div>
{% endblock %}

photologue/templates/photologue/tag_detail.html
{% extends "base.html" %}
{% comment %}
This file is part of photo21
Copyright (C) 2022  Amicale des élèves de l'ENS Paris-Saclay
SPDX-License-Identifier: GPL-3.0-or-later
{% endcomment %}
{% load i18n %}

{% block title %}{{ object.name }}{% endblock %}

{% block content %}
<h1>Tag : {{ object.name }}</h1>

<div class="row mb-2">
    {% for gallery in galleries %}
    <div class="col-6 col-md-3 mb-2">
        {% include "photologue/includes/gallery_sample.html" %}
    </div>
    {% endfor %}
</div>
{% endblock %}