photo21/urls.py
# This file is part of photo21
# Copyright (C) 2022  Amicale des élèves de l'ENS Paris-Saclay
# SPDX-License-Identifier: GPL-3.0-or-later

"""photo21 URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.2/topics/http/urls/
"""

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, re_path

from .views import IndexView, MediaAccess

urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("", include("photologue.urls", namespace="photologue")),
    path("accounts/", include("allauth.urls")),
    path("i18n/", include("django.conf.urls.i18n")),
    path("admin/doc/", include("django.contrib.admindocs.urls")),
    path("admin/", admin.site.urls),
]

# In production media are served through NGINX with X-Accel-Redirect
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    urlpatterns.append(
        re_path("^media/(?P<path>.*)", MediaAccess.as_view(), name="media")
    )

photologue/urls.py
# This file is part of photo21
# Copyright (C) 2022  Amicale des élèves de l'ENS Paris-Saclay
# SPDX-License-Identifier: GPL-3.0-or-later

from django.urls import path, re_path

from .views import (
    GalleryArchiveIndexView,
    GalleryDetailView,
    GalleryDownload,
    GalleryUpload,
    GalleryYearArchiveView,
    PhotoDeleteView,
    PhotoDetailView,
    PhotoReportView,
    TagDetail,
)

app_name = "photologue"
urlpatterns = [
    path("tag/<slug:slug>/", TagDetail.as_view(), name="tag-detail"),
    path("gallery/", GalleryArchiveIndexView.as_view(), name="pl-gallery-archive"),
    re_path(
        r"^gallery/(?P<year>\d{4})/$",
        GalleryYearArchiveView.as_view(),
        name="pl-gallery-archive-year",
    ),
    path("gallery/<slug:slug>/", GalleryDetailView.as_view(), name="pl-gallery"),
    path(
        "gallery/<slug:slug>/<int:owner>/",
        GalleryDetailView.as_view(),
        name="pl-gallery-owner",
    ),
    path(
        "gallery/<slug:slug>/download/",
        GalleryDownload.as_view(),
        name="pl-gallery-download",
    ),
    path("photo/<int:pk>/", PhotoDetailView.as_view(), name="pl-photo"),
    path("photo/<int:pk>/delete/", PhotoDeleteView.as_view(), name="pl-photo-delete"),
    path("photo/<int:pk>/report/", PhotoReportView.as_view(), name="pl-photo-report"),
    path("upload/", GalleryUpload.as_view(), name="pl-gallery-upload"),
]

photologue/models.py
# Based on https://github.com/richardbarran/django-photologue/
# by Richard Barran, BSD-3 licensed

import logging
import os
import random
import unicodedata
from datetime import datetime
from functools import partial
from importlib import import_module
from inspect import isclass
from io import BytesIO

import exifread
from django.conf import settings
from django.core.exceptions import ValidationError
from django.core.files.base import ContentFile
from django.core.validators import RegexValidator
from django.db import models
from django.template.defaultfilters import slugify
from django.urls import reverse
from django.utils.encoding import filepath_to_uri, force_str, smart_str
from django.utils.safestring import mark_safe
from django.utils.timezone import now
from django.utils.translation import gettext_lazy as _
from PIL import Image, ImageFile, ImageFilter

logger = logging.getLogger("photologue.models")

# Default limit for gallery.latest
LATEST_LIMIT = getattr(settings, "PHOTOLOGUE_GALLERY_LATEST_LIMIT", None)

# max_length setting for the ImageModel ImageField
IMAGE_FIELD_MAX_LENGTH = getattr(settings, "PHOTOLOGUE_IMAGE_FIELD_MAX_LENGTH", 100)

# Modify image file buffer size.
ImageFile.MAXBLOCK = getattr(settings, "PHOTOLOGUE_MAXBLOCK", 256 * 2**10)

# Look for user function to define file paths
PHOTOLOGUE_PATH = getattr(settings, "PHOTOLOGUE_PATH", None)
if PHOTOLOGUE_PATH is not None:
    if callable(PHOTOLOGUE_PATH):
        get_storage_path = PHOTOLOGUE_PATH
    else:
        parts = PHOTOLOGUE_PATH.split(".")
        module_name = ".".join(parts[:-1])
        module = import_module(module_name)
        get_storage_path = getattr(module, parts[-1])
else:

    def get_storage_path(instance, filename):
        fn = (
            unicodedata.normalize("NFKD", force_str(filename))
            .encode("ascii", "ignore")
            .decode("ascii")
        )
        return os.path.join("photos", fn)


# Exif Orientation values
# Value 0thRow	0thColumn
#   1	top     left
#   2	top     right
#   3	bottom	right
#   4	bottom	left
#   5	left	top
#   6	right   top
#   7	right   bottom
#   8	left    bottom

# Image Orientations (according to EXIF informations) that needs to be
# transposed and appropriate action
IMAGE_EXIF_ORIENTATION_MAP = {
    2: Image.FLIP_LEFT_RIGHT,
    3: Image.ROTATE_180,
    6: Image.ROTATE_270,
    8: Image.ROTATE_90,
}

# Quality options for JPEG images
JPEG_QUALITY_CHOICES = (
    (30, _("Very Low")),
    (40, _("Low")),
    (50, _("Medium-Low")),
    (60, _("Medium")),
    (70, _("Medium-High")),
    (80, _("High")),
    (90, _("Very High")),
)

# choices for new crop_anchor field in Photo
CROP_ANCHOR_CHOICES = (
    ("top", _("Top")),
    ("right", _("Right")),
    ("bottom", _("Bottom")),
    ("left", _("Left")),
    ("center", _("Center (Default)")),
)

IMAGE_TRANSPOSE_CHOICES = (
    ("FLIP_LEFT_RIGHT", _("Flip left to right")),
    ("FLIP_TOP_BOTTOM", _("Flip top to bottom")),
    ("ROTATE_90", _("Rotate 90 degrees counter-clockwise")),
    ("ROTATE_270", _("Rotate 90 degrees clockwise")),
    ("ROTATE_180", _("Rotate 180 degrees")),
)

# Prepare a list of image filters
filter_names = []
for n in dir(ImageFilter):
    klass = getattr(ImageFilter, n)
    if (
        isclass(klass)
        and issubclass(klass, ImageFilter.BuiltinFilter)
        and hasattr(klass, "name")
    ):
        filter_names.append(klass.__name__)
IMAGE_FILTERS_HELP_TEXT = _(
    'Chain multiple filters using the following pattern "FILTER_ONE->FILTER_TWO->FILTER_THREE"'
    ". Image filters will be applied in order. The following filters are available: %s."
    % (", ".join(filter_names))
)

size_method_map = {}


class TagField(models.CharField):
    """Tags have been removed from Photologue, but the migrations still refer to them so this
    Tagfield definition is left here.
    """

    def __init__(self, **kwargs):
        default_kwargs = {"max_length": 255, "blank": True}
        default_kwargs.update(kwargs)
        super().__init__(**default_kwargs)

    def get_internal_type(self):
        return "CharField"


class Gallery(models.Model):
    title = models.CharField(_("title"), max_length=250, unique=True)
    slug = models.SlugField(
        _("title slug"),
        unique=True,
        max_length=250,
        help_text=_('A "slug" is a unique URL-friendly title for an object.'),
    )
    date_start = models.DateField(
        default=now,
        verbose_name=_("start date"),
    )
    date_end = models.DateField(
        blank=True,
        null=True,
        verbose_name=_("end date"),
    )
    description = models.TextField(_("description"), blank=True)
    tags = models.ManyToManyField(
        "photologue.Tag",
        related_name="galleries",
        verbose_name=_("tags"),
        blank=True,
    )
    photos = models.ManyToManyField(
        "photologue.Photo",
        related_name="galleries",
        verbose_name=_("photos"),
        blank=True,
    )

    class Meta:
        ordering = ["-date_start"]
        get_latest_by = "date_start"
        verbose_name = _("gallery")
        verbose_name_plural = _("galleries")

    def __str__(self):
        return f"{ self.title } ({self.date_start})"

    def get_absolute_url(self):
        return reverse("photologue:pl-gallery", args=[self.slug])

    def sample(self, public=True):
        """Return a sample of photos, ordered at random."""
        count = 1
        if count > self.photo_count():
            count = self.photo_count()
        if public:
            photo_set = self.photos.filter(is_public=True)
        else:
            photo_set = self.photos
        return random.sample(list(photo_set), count)

    def photo_count(self, public=True):
        """Return a count of all the photos in this gallery."""
        if public:
            return self.photos.filter(is_public=True).count()
        else:
            return self.photos.count()

    def photo_private_count(self):
        """Return a count of private photos in this gallery."""
        return self.photos.filter(is_public=False).count()

    photo_count.short_description = _("count")
    photo_private_count.short_description = _("private count")


class ImageModel(models.Model):
    image = models.ImageField(
        _("image"), max_length=IMAGE_FIELD_MAX_LENGTH, upload_to=get_storage_path
    )
    date_taken = models.DateTimeField(
        _("date taken"),
        null=True,
        blank=True,
        help_text=_("Date image was taken; is obtained from the image EXIF data."),
    )
    view_count = models.PositiveIntegerField(_("view count"), default=0, editable=False)
    crop_from = models.CharField(
        _("crop from"),
        blank=True,
        max_length=10,
        default="center",
        choices=CROP_ANCHOR_CHOICES,
    )

    class Meta:
        abstract = True

    def exif(self, file=None):
        try:
            if file:
                tags = exifread.process_file(file)
            else:
                with self.image.storage.open(self.image.name, "rb") as file:
                    tags = exifread.process_file(file, details=False)
            return tags
        except Exception:
            return {}

    def admin_thumbnail(self):
        func = getattr(self, "get_admin_thumbnail_url", None)
        if func is None:
            return _('An "admin_thumbnail" photo size has not been defined.')
        else:
            if hasattr(self, "get_absolute_url"):
                return mark_safe(
                    '<a href="{}"><img src="{}"></a>'.format(
                        self.get_absolute_url(), func()
                    )
                )
            else:
                return mark_safe(
                    '<a href="{}"><img src="{}"></a>'.format(self.image.url, func())
                )

    admin_thumbnail.short_description = _("Thumbnail")
    admin_thumbnail.allow_tags = True

    def cache_path(self):
        return os.path.join(os.path.dirname(self.image.name), "cache")

    def cache_url(self):
        if not self.image:
            return ""
        return "/".join([os.path.dirname(self.image.url), "cache"])

    def image_filename(self):
        return os.path.basename(force_str(self.image.name))

    def _get_filename_for_size(self, size):
        size = getattr(size, "name", size)
        base, ext = os.path.splitext(self.image_filename())
        return "".join([base, "_", size, ext])

    def _get_size_photosize(self, size):
        return PhotoSizeCache().sizes.get(size)

    def _get_size_size(self, size):
        photosize = PhotoSizeCache().sizes.get(size)
        if not self.size_exists(photosize):
            self.create_size(photosize)
        try:
            return Image.open(
                self.image.storage.open(self._get_size_filename(size))
            ).size
        except Exception:
            return None

    def _get_size_url(self, size):
        photosize = PhotoSizeCache().sizes.get(size)
        if not self.size_exists(photosize):
            self.create_size(photosize)
        if photosize.increment_count:
            self.increment_count()
        return "/".join(
            [
                self.cache_url(),
                filepath_to_uri(self._get_filename_for_size(photosize.name)),
            ]
        )

    def _get_size_filename(self, size):
        photosize = PhotoSizeCache().sizes.get(size)
        return smart_str(
            os.path.join(self.cache_path(), self._get_filename_for_size(photosize.name))
        )

    def increment_count(self):
        self.view_count += 1
        models.Model.save(self)

    def __getattr__(self, name):
        global size_method_map
        if not size_method_map:
            init_size_method_map()
        di = size_method_map.get(name, None)
        if di is not None:
            result = partial(getattr(self, di["base_name"]), di["size"])
            setattr(self, name, result)
            return result
        else:

photo21/forms.py
# This file is part of photo21
# Copyright (C) 2022  Amicale des élèves de l'ENS Paris-Saclay
# SPDX-License-Identifier: GPL-3.0-or-later

from allauth.account.forms import SignupForm
from django import forms
from django.utils.translation import gettext_lazy as _


class CustomSignupForm(SignupForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # Add description on email field
        self.fields["email"].help_text = _(
            "Please enter a valid email address ending with `@crans.org` or "
            "`@ens-paris-saclay.fr`."
        )

    def clean_email(self):
        """
        Check that the email address ends with a trusted domain.
        """
        email = super().clean_email()
        if not email.endswith("@crans.org") and not email.endswith(
            "@ens-paris-saclay.fr"
        ):
            raise forms.ValidationError(
                _("Must end with `@crans.org` or `@ens-paris-saclay.fr`.")
            )
        return email

photo21/views.py
# This file is part of photo21
# Copyright (C) 2021-2022  Amicale des élèves de l'ENS Paris-Saclay
# SPDX-License-Identifier: GPL-3.0-or-later

from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse
from django.views.generic import ListView, View
from photologue.models import Gallery


class MediaAccess(LoginRequiredMixin, View):
    def get(self, request, path):
        response = HttpResponse()
        # Content-type will be detected by nginx
        del response["Content-Type"]
        response["X-Accel-Redirect"] = "/protected/media/" + path
        return response


class IndexView(LoginRequiredMixin, ListView):
    queryset = Gallery.objects.all()
    paginate_by = 4
    template_name = "index.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # Get superusers
        user_model = get_user_model()
        superusers = user_model.objects.filter(is_superuser=True)
        context["superusers"] = superusers

        return context

photo21/templates/base.html
{% comment %}
This file is part of photo21
Copyright (C) 2022  Amicale des élèves de l'ENS Paris-Saclay
SPDX-License-Identifier: GPL-3.0-or-later
{% endcomment %}
{% load static i18n %}
<!DOCTYPE html>
{% get_current_language as LANGUAGE_CODE %}{% get_current_language_bidi as LANGUAGE_BIDI %}
<html lang="{{ LANGUAGE_CODE|default:"en" }}"{% if LANGUAGE_BIDI %} dir="rtl"{% endif %} data-bs-theme="dark">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Security-Policy" content="default-src 'self'; img-src 'self' data:; script-src 'self'; style-src 'self' 'unsafe-inline'; font-src 'self'">
    <meta http-equiv="Referrer-Policy" content="no-referrer">
    <title>{% block title %}{{ title }}{% endblock title %} - {{ request.site.name }}</title>
    <meta name="description" content="{% trans "The ENS Paris-Saclay pictures server." %}">
    <link rel="stylesheet" href="{% static "bootstrap5/css/bootstrap.min.css" %}">
    <link rel="stylesheet" href="{% static "layout.css" %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static "favicon-16x16.png" %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static "favicon-32x32.png" %}">
    <meta name="theme-color" content="#212529">
    {% block extracss %}{% endblock %}
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary py-0">
        <div class="container">
            <a class="navbar-brand" href="{% url 'index' %}">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" viewBox="0 0 16 20">
                    <path d="M4.502 9a1.5 1.5 0 1 0 0-3 1.5 1.5 0 0 0 0 3z"/>
                    <path d="M14.002 13a2 2 0 0 1-2 2h-10a2 2 0 0 1-2-2V5A2 2 0 0 1 2 3a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2v8a2 2 0 0 1-1.998 2zM14 2H4a1 1 0 0 0-1 1h9.002a2 2 0 0 1 2 2v7A1 1 0 0 0 15 11V3a1 1 0 0 0-1-1zM2.002 4a1 1 0 0 0-1 1v8l2.646-2.354a.5.5 0 0 1 .63-.062l2.66 1.773 3.71-3.71a.5.5 0 0 1 .577-.094l1.777 1.947V5a1 1 0 0 0-1-1h-10z"/>
                </svg>
                {{ request.site.name }}
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        {% url 'photologue:pl-gallery-archive' as url %}
                        <a class="nav-link {% if request.path_info == url %}active{% endif %}" href="{{ url }}">{% trans 'Galleries' %}</a>
                    </li>
                    {% if perms.photologue.add_gallery %}
                    <li class="nav-item">
                        {% url 'photologue:pl-gallery-upload' as url %}
                        <a class="nav-link {% if request.path_info == url %}active{% endif %}" href="{{ url }}">{% trans 'Upload' %}</a>
                    </li>
                    {% endif %}
                    {% if request.user.is_staff %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'admin:index' %}">{% trans 'Manage' %}</a>
                    </li>
                    {% endif %}
                </ul>
                <ul class="navbar-nav">
                    {% if request.user.is_authenticated %}
                        <li class="nav-item">
                            {% url 'account_email' as url %}
                            <a class="nav-link {% if request.path_info == url %}active{% endif %}" href="{{ url }}">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person" viewBox="0 0 16 16">
                                    <path d="M8 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0zm4 8c0 1-1 1-1 1H3s-1 0-1-1 1-4 6-4 6 3 6 4zm-1-.004c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664h10z"/>
                                </svg>
                                {% trans "Account" %}
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'account_logout' %}">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-box-arrow-right" viewBox="0 0 16 16">
                                    <path fill-rule="evenodd" d="M10 12.5a.5.5 0 0 1-.5.5h-8a.5.5 0 0 1-.5-.5v-9a.5.5 0 0 1 .5-.5h8a.5.5 0 0 1 .5.5v2a.5.5 0 0 0 1 0v-2A1.5 1.5 0 0 0 9.5 2h-8A1.5 1.5 0 0 0 0 3.5v9A1.5 1.5 0 0 0 1.5 14h8a1.5 1.5 0 0 0 1.5-1.5v-2a.5.5 0 0 0-1 0v2z"/>
                                    <path fill-rule="evenodd" d="M15.854 8.354a.5.5 0 0 0 0-.708l-3-3a.5.5 0 0 0-.708.708L14.293 7.5H5.5a.5.5 0 0 0 0 1h8.793l-2.147 2.146a.5.5 0 0 0 .708.708l3-3z"/>
                                </svg>
                                {% trans "Log out" %}
                            </a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'account_login' %}">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-box-arrow-in-right" viewBox="0 0 16 16">
                                    <path fill-rule="evenodd" d="M6 3.5a.5.5 0 0 1 .5-.5h8a.5.5 0 0 1 .5.5v9a.5.5 0 0 1-.5.5h-8a.5.5 0 0 1-.5-.5v-2a.5.5 0 0 0-1 0v2A1.5 1.5 0 0 0 6.5 14h8a1.5 1.5 0 0 0 1.5-1.5v-9A1.5 1.5 0 0 0 14.5 2h-8A1.5 1.5 0 0 0 5 3.5v2a.5.5 0 0 0 1 0v-2z"/>
                                    <path fill-rule="evenodd" d="M11.854 8.354a.5.5 0 0 0 0-.708l-3-3a.5.5 0 1 0-.708.708L10.293 7.5H1.5a.5.5 0 0 0 0 1h8.793l-2.147 2.146a.5.5 0 0 0 .708.708l3-3z"/>
                                </svg>
                                {% trans "Log in" %}
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'account_signup' %}">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person-plus" viewBox="0 0 16 16">
                                    <path d="M6 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0zm4 8c0 1-1 1-1 1H1s-1 0-1-1 1-4 6-4 6 3 6 4zm-1-.004c-.001-.246-.154-.986-.832-1.664C9.516 10.68 8.289 10 6 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664h10z"/>
                                    <path fill-rule="evenodd" d="M13.5 5a.5.5 0 0 1 .5.5V7h1.5a.5.5 0 0 1 0 1H14v1.5a.5.5 0 0 1-1 0V8h-1.5a.5.5 0 0 1 0-1H13V5.5a.5.5 0 0 1 .5-.5z"/>
                                </svg>
                                {% trans "Sign up" %}
                            </a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>

    <main class="container my-3">
        {% for message in messages %}
            <div class="alert {{ message.tags }} alert-dismissible" role="alert" >
                {{ message }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        {% endfor %}
        {% block content %}
            <p>Default content...</p>
        {% endblock %}
    </main>
    <footer>
        <form action="{% url 'set_language' %}" method="post">
            {% csrf_token %}
            <p class="small text-center text-muted mt-1">
                {% if request.user.is_authenticated %}
                    {% trans "Connected as" %} <code>{{ request.user.username }}</code> &middot;
                {% endif %}
                <a class="text-reset" href="https://gitlab.crans.org/bde/photo21/">{% trans "Source code" %}</a> &middot;
                <select title="language" name="language" class="lang-select">
                    {% get_current_language as LANGUAGE_CODE %}
                    {% get_available_languages as LANGUAGES %}
                    {% for lang_code, lang_name in LANGUAGES %}
                        <option value="{{ lang_code }}" {% if lang_code == LANGUAGE_CODE %}selected{% endif %}>
                            {{ lang_name }} ({{ lang_code }})
                        </option>
                    {% endfor %}
                </select>
                <noscript><input type="submit"></noscript>
            </p>
        </form>
    </footer>

    <script src="{% static "lang-select.js" %}"></script>
    <script src="{% static "bootstrap5/js/bootstrap.bundle.min.js" %}"></script>
    {% block extrajs %}{% endblock %}
</body>
</html>

photo21/templates/index.html
{% extends "base.html" %}
{% comment %}
This file is part of photo21
Copyright (C) 2022  Amicale des élèves de l'ENS Paris-Saclay
SPDX-License-Identifier: GPL-3.0-or-later
{% endcomment %}
{% load i18n %}
{% block title %}{% trans "Home" %}{% endblock %}

{% block content %}
    <h2>{% trans "Welcome to the pictures server!" %}</h2>
    <p>
        {% blocktrans trimmed %}
        This website aims to collect the pictures and movies taken in the student
        life of ENS Paris-Saclay or involving its students.
        {% endblocktrans %}
    </p>
    <p>
        {% url 'photologue:pl-gallery-archive' as gallery_archive_url %}
        {% blocktrans trimmed %}
        The pictures are visible in <a href="{{ gallery_archive_url }}">the galleries</a>
        and are downloadable.
        <b>However, the agreement of the photographer and the persons present
        on the photo is necessary before any republication on another platform. </b>
        {% endblocktrans %}
    </p>

    <p>
        {% blocktrans trimmed %}
        If you want a photo to be deleted, please let us know:
        <a href="mailto:photos@crans.org?subject=[ABUS] Nouvelle requête" class="btn btn-secondary btn-sm">Abuse request</a>
        {% endblocktrans %}
    </p>
    {% if not perms.photologue.add_photo %}
    <p>
        {% blocktrans trimmed %}
        If you want to obtain the right to upload pictures, please let us know:
        <a href="mailto:photos@crans.org?subject=[Photographe] Demande de droits photographe" class="btn btn-secondary btn-sm">Become a photograph</a>
        {% endblocktrans %}
    </p>
    {% endif %}

    <h3>{% trans "Last galleries" %}</h3>
    <div class="row mb-2">
        {% for gallery in object_list %}
        <div class="col-md-3">
            {% include "photologue/includes/gallery_sample.html" %}
        </div>
        {% endfor %}
    </div>

    <h3 class="mt-4">{% trans "Behind the scene" %}</h3>
    <p>
        {% blocktrans trimmed %}
        Because we value your privacy, we do not sell the data on this site,
        unlike many free online platforms.
        The dedicated server running this website is kindly hosted by the
        <a href="https://www.crans.org/">Crans</a> at the ENS Paris-Saclay
        basement.
        It is not managed by the Crans. Current active administrators are:
        {% endblocktrans %}
        {% for user in superusers %} <code>{{ user.username }}</code>{% endfor %}.
        {% trans "They should be contacted at" %}
        <a href="mailto:photos@crans.org">photos@crans.org</a>.
    </p>
{% endblock %}